name: Update Playlist Weekly

on:
  schedule:
    - cron: '0 2 * * 4'  # Run every Thursday at 2:00 AM UTC

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout automated branch
        uses: actions/checkout@v4
        with:
          ref: automated

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '14'

      - name: Run script.js from automated branch
        run: |
          node script.js  # Assuming script.js is in the root directory
